konveyor/kai

.github/workflows/trunk-check-annotations.yml
.github/workflows/trunk-check.yml

Addresses: 
"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."
https://github.com/konveyor-ecosystem/kai/actions/runs/7729866097

Bump github actions check to address deprecated warning

---

kai/__init__.py
kai/incident_store.py
tests/test_incident_store.py

My first stab at incident store
1. There is a load method that takes the list of applications and loads the cached violations data store.
Sample command to run `./run_cli.py load kitchensink,eap-coolstore-monolith`
2. writes to `samples/generated_output/incident_store/cached_violations.yaml`

Loading Incident store

---

samples/fetch_analyze_apps.py

@jwmatthews This script ran for ~300 min and most of the time was consumed by coolstore and ticketmonster. 
I have the analysis output files updated for apps except bmt/cmt. Could be because of running them against latest kantra build. Should I commit them here?

automating cloning and analysis

---

requirements.txt

Fedora 39 uses python 3.12. aiohttp 3.8.6 does not work with it.

Set aiohttp version based on python version

---

run_tests.sh
tests/test_incident_store.py

I wasn't able to run unit tests today, noticed 2 failures that needed a tweak to address

Restore run_tests.sh to run without an errors

---

example/run_demo.py

- Creates a <srcfilename>.reasoning file as output for each generated file
- Changes client to use KAI_LOG so we have timestamps on output
- Adds start/time to requests to get an idea of how long they are taking
Full client console output: https://gist.github.com/jwmatthews/d1af9b06a29c38ff9dd934225216c228
Sample:
```
INFO - 2024-03-26 13:28:19,794 - [run_demo.py:203 -             run_demo() ] - 2 files remaining from total of 26
INFO - 2024-03-26 13:30:23,443 - [run_demo.py:172 -         process_file() ] - Response StatusCode: 200 for src/main/java/com/redhat/coolstore/service/ShoppingCartOrderProcessor.java
INFO - 2024-03-26 13:30:23,443 - [run_demo.py:138 -        write_to_disk() ] - Writing updated source code to ./coolstore/src/main/java/com/redhat/coolstore/service/ShoppingCartOrderP …
```

Capturing reasoning info and writing to disk plus small tweaks to client for logging and gathering timing info

---

Makefile
example/run_demo.py
kai/server.py

Fixes #109 
One of the calls (15 incidents in the file) took 2864s which is why the previous timeouts weren't allowing the demo to finish running.
```
./run_demo.py  1.63s user 0.33s system 0% cpu 1:06:46.71 total
```
This solution won't scale though, we probably need to either chunk incidents (ie only send x at a time) or maybe the work that @JonahSussman is working on will fix it

Add retry mechanism and increase timeouts for file resolution

---

example/list_violations_for_file.py

Example of using this to find the violations associated to a given file.
```
$ time ./list_violations_for_file.py "src/main/java/com/redhat/coolstore/service/ShippingService.java"
INFO - 2024-03-27 14:11:55,281 - [report.py:79 -         _read_report() ] - Reading report from ./analysis/coolstore/output.yaml
File 'src/main/java/com/redhat/coolstore/service/ShippingService.java' has the following violations:
eap8/eap7 javax-to-jakarta-import-00001 at line 6
eap8/eap7 javax-to-jakarta-import-00001 at line 7
kai/quarkus remote-ejb-to-quarkus-00000 at line 12
quarkus/springboot cdi-to-quarkus-00050 at line 11
./list_violations_for_file.py   1.81s user 1.56s system 294% cpu 1.144 total
```
```
$ time ./list_violations_for_file.py "pom.xml"
INFO - 2024-03-27 14:12:22,635 - [report.py:79 - …
```

List the violations for a given file

---

README.md

The demo instructions start with cloning the repo.
The first step is `git clone https://github.com/konveyor-ecosystem/kai.git`. If you do this you haven't fetched the sample apps yet. If you run make load without doing it first you'll get the following error:
```
...kai/env/lib64/python3.12/site-packages/git/repo/base.py", line 215, in __init__
raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/jason/Documents/go/src/github.com/konveyor-ecosystem/kai/samples/sample_repos/bmt
make: *** [Makefile:16: load-data] Error 1
```

Add fetching sample apps step to demo

---

example/run_demo.py
kai/pydantic_models.py
kai/server.py

Fixes #122 
- Add language guesser and use it to more intelligently select code blocks from response
- Don't count incomplete responses as successful
- Retries when updated file content is not parsed
- Only attempts to find code block content underneath the Updated File header in order to avoid grabbing extra info from reasoning
- Add support for returning LLM results directly on the server and saving it from the demo client

Make parsing of LLM response more robust

---

kai/model_provider.py

I missed a comma for the granite config in prior PR, which results in the below error when trying to use granite-13b
```
Exception: Invalid model_id: ibm/granite-13b-chat-v2
Valid models: ibm/granite-20b-code-instruct-v1ibm/granite-13b-chat-v2
```

Fix use of granite13b, was missing a comma in prior commit

---

kai/model_provider.py

Juanma stated that the results improved after making these changes in combination with prompt changes.
https://github.com/konveyor-ecosystem/coolstore/pull/19
temperature 0.05 is the minimum IBM accepts and will probably generally result in more reproducible results, but open to discussing adjusting any of these.

Update IBM / OpenSource default values

---

kai/server.py

Exclude the cookie header from recorded cassettes so OpenAI calls will properly cache in demo mode

---

example/run_demo.py

If `KAI_MAX_WORKERS` is set I get an error from `run_demo.py`: `TypeError: '<=' not supported between instances of 'str' and 'int'`

Fix max_workers comparison in run_demo.py

---

kai/server.py

We removed the kai-service directory so this comment is now outdated.

:ghost: Remove outdated comment

---

.github/workflows/evaluation.yml

This should start generating graphs at https://konveyor-ecosystem.github.io/kai/ or a URL close to that.
And example of what this will look like is here:
https://jmontleon.github.io/kai/
- I have pushed a mostly empty gh-pages branch with just a README.md to prepare for this.
- We need to add a `GENAI_KEY` secret before this will work. I don't currently appear to have access to do this.
- Likewise with enabling GitHub Pages to use the gh-pages branch similar to:

Add Evaluation GH Action

---

.github/workflows/evaluation.yml

Pinning to 3.12.3 should no longer be necessary.
https://github.com/konveyor-ecosystem/kai/issues/215
https://github.com/konveyor-ecosystem/kai/pull/216

:ghost: Unpin python version in evaluation action

---

build/entrypoint.sh
compose.yaml

This is currently blocking the kubernetes operator deployment.

:bug: Allow database host to be configured and respected in the entrypoint

---

example/README.md

:book: Update README.md to fix broken links

---

kai/kai_logging.py

This PR closes #278. It addresses an issue with the `process_log_dir_replacements` function, which is responsible for replacing the $pwd placeholder in log directory paths with the path to the Kai project directory. The original function returned paths with redundant components and did not correctly resolve relative paths.
The original function produced paths with incorrect or redundant components, such as /home/k8smaster/Desktop/kai/kai/..//logs, leading to errors and misconfiguration in the log directory paths.
Function Update: Updated the process_log_dir_replacements function to:
Replace $pwd with the path to the Kai project directory, one level up from the current working directory.
Normalize the resulting path to remove redundant components and resolve relative path issues.
```
def …
```

fix: Fix Path Resolution in `process_log_dir_replacements` Function

---

README.md
docs/Getting_Started.md
docs/contrib/Tracing.md
docs/design/solvedIncidentStore.md
docs/scenarios/demo.md

Small typo and broken link update

:book: Update Getting_Started.md fix typo and broken link

---

kai/test_kai_logging.py

Added unit tests for kai_logging.py to ensure proper functionality of logging setup. Tests cover:
- process_log_dir_replacements
- setup_console_handler
- setup_file_handler
- initLogging
- initLoggingFromConfig

test: Add test for kai_logging.py

---

docs/customApps.md

Added explicit steps for configuring and using custom rules.

---

kai/evaluation.py

This PR addresses an inconsistency in the type annotation of the `print_nicely_formatted_comparison` function in `evaluation.py`.
Changes made:
- Updated the type hint for the `results` parameter from `dict[tuple[str, str], BenchmarkExample]` to `dict[tuple[str, str], BenchmarkResult]`
Reason for change:
The function was accessing a `similarity` attribute which is present in `BenchmarkResult` but not in `BenchmarkExample`. This change aligns the type annotation with the actual usage in the function, preventing potential runtime errors and improving type checking.
Related issue: closes #290 
Please review and let me know if any further changes are needed.

Fix type annotation in print_nicely_formatted_comparison function

---

kai/service/solution_handling/test_consumption.py

This PR introduces unit tests for the `consumption.py` in the `kai.service.solution_handling.consumption` module. The tests cover the following functionalities:
- solution_consumer_diff_only
- solution_consumer_before_and_after
- solution_consumer_llm_summary
- solution_consumer_factory

test: Add Unit Tests for `consumption.py`

---

build/entrypoint.sh
compose.yaml

We are not making use of vector, so switching to the same image that we use in konveyor upstream. This is also similar to the UBI image we use downstream.
https://github.com/konveyor/operator/blob/main/bundle/manifests/konveyor-operator.clusterserviceversion.yaml#L280C26-L280C65

:ghost: Update compose DB image

---

build/entrypoint.sh
kai/hub_importer.py

- [🐛 When importer args aren't provided, don't use empty string as url](https://github.com/konveyor/kai/pull/309/commits/a4625184262c310e7d78da9029e13bb5a82599a2)
- [🐛 Pass analysis ID in when report is loaded](https://github.com/konveyor/kai/pull/309/commits/52a1731817a33deb969e036c99524c1b43cdd1c8)

Fixes blocking Kai integration

---

kai/kai_trace.py
kai/service/kai_application/kai_application.py

**Capture Number of Tokens in Request and Response**
When this PR is merged, you will be able to capture metadata from the responses into the trace directory when you run [run_demo.py](https://github.com/konveyor/kai/blob/main/example/run_demo.py) . The structure will be as follows:
```bash
── trace
└── gpt-3.5-turbo << MODEL ID>>
└── coolstore << APP Name >>
├── pom.xml << Source File Path >>
│   └── single_group << Incident Batch Mode >>
│       └── 1719673609.8266618 << Start of Request Time Stamp >>
│           ├── 1 << Incident Batch Number >>
│           │   ├── 0 << Retry Attempt  >>
│           │   │   ├── llm_result << Contains the response from the LLM prior to us parsing >>
│           │   │   ├── token_usage.json<< New metadata file added here >>
│           │   │   ├── prompt …
```

Add metadata to tracing

---

kai/hub_importer.py

Update the importer to pass the auth token to the hub.

:sparkles: importer: Pass auth token.

---

Makefile
example/run_demo.py
kai/kai_trace.py
kai/service/kai_application/kai_application.py

This is builds on #375.
I saw while testing that not all providers sent back the same keys in 'response_metadata'.
For example Bedrock has the key 'usage' and IBM BAM and Groq have the key 'token_usage'.
To keep things simple, I'm proposing we log all response_metadata to disk and not look for a specific key.
This PR also updates the server to send back the responses metadata in it's result so the client can access it.

Change from token_usage to all response metadata

---

playpen/repo_level_awareness/api.py
playpen/repo_level_awareness/codeplan.py
playpen/repo_level_awareness/task_runner/analyzer_lsp/api.py
playpen/repo_level_awareness/task_runner/compiler/maven_validator.py
playpen/repo_level_awareness/tests/test_priority_queue.py

Rather than a simple list of tasks, maintain a priority queue of Task stacks, where new issues spawned from work on a task are added as children of the main task. This allows us to focus on the most relevant issues first, and gives us knobs to play with by being able to tweak the priority of individual tasks/task classes
closes #409

Add a hierarchical task structure

---

kai/config.toml
kai/kai_trace.py
kai/models/kai_config.py
kai/service/kai_application/kai_application.py
kai/service/kai_application/test_kai_application.py

After merging this PR, token estimates based on the input prompt will be available. Depending on the model being used, the [encoding base ](https://github.com/openai/tiktoken/blob/main/tiktoken/model.py)for Tiktoken can be adjusted to improve the accuracy of the input prompt estimates. The encoding configuration can be updated by modifying the token encoding base setting in the [`config.toml`](https://github.com/devjpt23/kai/blob/prompt-token-estimation/kai/config.toml) file.
```bash
log_level = "info"
file_log_level = "debug"
log_dir = "$pwd/logs"
demo_mode = false
trace_enabled = true
token_estimation_encoding_base = "gpt-4o"  <===== Encoding base
...
```
Futhermore, the estimates of the prompt tokens are saved in a file `estimated_tokens.json`
```bash
TRACE DIRECTORY
── trace
└── …
```

Integration of Token Estimation for Input Prompts

---

kai/reactive_codeplanner/main.py
kai/reactive_codeplanner/task_manager/api.py
kai/reactive_codeplanner/task_manager/priority_queue.py
kai/reactive_codeplanner/task_manager/task_manager.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/api.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/validator.py

Also allows children to maintain their original priority level (for sorting) while remaining in the queue of their oldest ancestor

:bug: Prevent circular parent-child task relationships

---

kai/reactive_codeplanner/main.py
kai/reactive_codeplanner/task_manager/api.py
kai/reactive_codeplanner/task_manager/priority_queue.py
tests/test_task_manager.py

- Changes `__lt__` behavior of tasks to do depth then priority
- Fixes the priority queue sort when a task is appended so that it can pop the next task properly
- Adds a `__str__` function to the priority queue for easier introspection during debugging
- Adds timing information and queue state logging to the `reactive_codeplanner/main.py`, to aid debugging

:bug: Priority Queue now always returns highest depth tasks for a given priority level first

---

kai/reactive_codeplanner/agent/maven_compiler_fix/agent.py
kai/reactive_codeplanner/task_runner/compiler/compiler_task_runner.py
kai/reactive_codeplanner/task_runner/compiler/maven_validator.py
kai/reactive_codeplanner/task_runner/dependency/task_runner.py
tests/test_maven_compiler_agent.py
tests/test_maven_validator.py

- Introduces two new error types, `BuildError` and `DependencyResolutionError`, which are now detected and parsed
- Adds a catchall condition if maven exits non-zero but no errors are successfully parsed so that we have a chance at solving the issue
- Restructures the maven_validator as the parsing logic was getting unwieldy
- The maven task_runner no longer adds whitespace at the top of files
- The dependency task_runner now properly checks the tasks it can handle
- Adds tests for maven validator

:sparkles: Maven Validator now properly detects and reports build errors

---

kai/reactive_codeplanner/task_runner/compiler/maven_validator.py
tests/test_maven_validator.py

- This prevents the errors from erroneously being removed from the queue

:bug: Maven validator now caches compilation errors when project can't build

---

kai/reactive_codeplanner/task_manager/api.py

- This allows the manual prioritization by type to still have effect when dealing with seed tasks

:bug: Default priority is used for sorting within a stack

---

Makefile
example/run_demo.py
kai/reactive_codeplanner/task_manager/priority_queue.py
kai/reactive_codeplanner/task_manager/task_manager.py
kai/rpc_server/server.py

- Adds `set_seed_tasks` method to `TaskManager`, which replaces the current set of seed tasks with a new one
- The server now initializes the `TaskManager` only once, and maintains queue state between calls. The `set_seed_tasks` method is used to reset the top-level priority queue.
- Removes `max_iterations` from inside the `task_manager`. Instead, the caller of `get_next_task` can maintain the iterations outside the loop. The rpc server has been updated to handle this.
- Changes `run_demo` default `max_iterations` to the number of incidents in a file
- Adds more logging throughout the server + demo to better aid debugging, particularly when the process hangs
- Adds/refines make targets for running the demos + debug driver more consistently
- Sets the default analysis rules path to …

:sparkles: Seeds tasks can now be set at any time

---

pyproject.toml

This should hopefully fix some issues that people are having when trying to run Kai on MacOS.

:bug: Moved solution server dependencies out from main dependency block

---

kai/reactive_codeplanner/agent/dependency_agent/util.py

Fix Maven Central FQDN Search for Dependency Agent
- Handle Maven Central search responses without latest version
- Return None when no valid dependency version is found

:bug: Fix for #478 KeyError: 'latestVersion'

---

kai/analyzer_types.py

Fixing types for mypy
StringIO does not type to TextIOWrapper[_BufferedWrapper], there is no issue using StringIO AFAICT so just using that

:ghost: Fixing types for mypy

---

.github/workflows/build-and-push-binaries.yml

Fixes #520 
Here is an example of a calling workflow that can use this workflow. It runs this workflow to build Kai binaries for all platforms and does its own things on the same platforms:
```
name: test
on:
workflow_dispatch:
jobs:
kai_build:
uses: konveyor/kai/.github/workflows/build-and-push-binaries.yml@main
plugin_build:
name: plugin build
needs: kai_build
strategy:
matrix:
runs_on: ${{ fromJson(needs.kai_build.outputs.matrix_info) }}
runs-on: ${{ matrix.runs_on.os }}
steps:
- name: Download kai binaries
uses: actions/download-artifact@v3
with:
name: kai-rpc-server.${{ env.OS }}-${{ env.OS_ARCH }}.zip
path: kai-rpc-server.${{ env.OS }}-${{ env.OS_ARCH }}.zip
- name: Build and package the IDE plugin
run: | 
```

:ghost: make release workflow callable

---

kai/reactive_codeplanner/task_manager/task_manager.py

- When adding seed tasks, clear processed/ignored tasks so that we try to solve anything we see
closes #580

:bug: Don't allow seed tasks to be skipped

---

kai/analyzer.py
kai/rpc_server/server.py

I have tried to Implement exception handling in analyzer initialization to:
- Detect analyzer startup failures
- Stop RPC server when analyzer cannot start
Solves #537

:bug: Ensure Kai RPC Server Stops When Analyzer-LSP-RPC Fails 

---

kai/reactive_codeplanner/agent/dependency_agent/dependency_agent.py
kai/reactive_codeplanner/agent/maven_compiler_fix/agent.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/api.py
kai/reactive_codeplanner/task_runner/compiler/compiler_task_runner.py
kai/reactive_codeplanner/task_runner/compiler/maven_validator.py
kai/rpc_server/server.py
pyproject.toml

* This also adds the clean option to maven, so that maven is recompiled every time; this is needed when the pom.xml does not yet have the maven compiler plugin.
* The line numbers are not used in the dependency agent; because of this, we can assume we know that we don't need to pass it through.

:sparkles: package/symbol not found errors are now collapsable for file

---

kai/llm_interfacing/model_provider.py

The default implementation of `_default_params` and `_get_request_payload` on `ChatOpenAI` automatically converts `max_completion_tokens` to `max_tokens`, which is undesirable for certain OpenShift AI instances.
[link](https://github.com/langchain-ai/langchain/blob/db8201d4dafb533133cc51c87c7ef011e546e03f/libs/partners/openai/langchain_openai/chat_models/base.py#L1992-L2013)
```python
@property
def _default_params(self) -> Dict[str, Any]:
"""Get the default parameters for calling OpenAI API."""
params = super()._default_params
if "max_tokens" in params:
params["max_completion_tokens"] = params.pop("max_tokens")
return params
def _get_request_payload(
self,
input_: LanguageModelInput,
*,
stop: Optional[List[str]] = None,
**kwargs: Any,
) -> dict:
payload = …
```

:bug: Fixed default params for openai

---

kai/cache.py
kai/llm_interfacing/model_provider.py
tests/test_cache.py

Fixes #636 
This makes it so that when paths become too long, they are flattened at the root task's level, so we still get hierarchy as much as we can but leave the too many nested stuff flattened which is probably pita to navigate anyway

:bug: fix cache paths when they become too long to handle

---

kai/cache.py
kai/reactive_codeplanner/task_manager/api.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/api.py
kai/reactive_codeplanner/task_runner/compiler/maven_validator.py
tests/test_cache.py

* This makes it easier to determine what the path should be for each task, as tasks have more and more divergent data
* Removes the cache overwrite for SymbolNotFound and PackageDoesNotExistErrors
* Adds the depth to file tree to see effort level at work.
* In the future we should consider enhancing this, so that tasks can add data to the trace to make debugging even easier

:sparkles: Adding cache file name resolution to the task's

---

.trunk/configs/custom-words.txt
kai/cache.py
kai/llm_interfacing/model_provider.py
kai/reactive_codeplanner/agent/dependency_agent/dependency_fqdn_selection.py
kai/reactive_codeplanner/agent/maven_compiler_fix/agent.py
kai/reactive_codeplanner/task_runner/compiler/compiler_task_runner.py
kai/reactive_codeplanner/task_runner/dependency/api.py
kai/reactive_codeplanner/task_runner/dependency/task_runner.py

* Make it so that the FQDN agent doesn't cause LLM to cycle on itself
* Make it so the FQDN agent has a system prompt, that will help with
context window issues
* Make it so that the SymbolNotFound issues go to the maven compiler.
This is because if the dependency is missing from the project both a
symbol not found and a package does not exist are created. If just a
symbol not found, then the issue is the Class changed.
This is built on #653 to make debugging easier. 
After this change, with openshift-ai, I can fix the DatabaseMigrationStartup.java file in around 6 minutes, where before it was taking upwards of 20-30. 
fixes #650

:bug: Fixing up the symbol not found and dependency agents 

---

kai/rpc_server/server.py

:bug: Added back the reset of the repository before we send the response back

---

.trunk/configs/custom-words.txt
kai/llm_interfacing/model_provider.py
kai/reactive_codeplanner/agent/analyzer_fix/agent.py
kai/reactive_codeplanner/main.py
kai/reactive_codeplanner/task_manager/task_manager.py
kai/rpc_server/server.py
kai_solution_server/service/incident_store/incident_store.py
pyproject.toml
tests/test_analyzer_agent.py
tests/test_dependency_task_runner.py
tests/test_incident_store.py
tests/test_maven_compiler_agent.py
tests/test_model_provider.py
tests/test_reflection_agent.py

Closes #136 
Closes #350
I refactored `model_provider.py`, putting each `ModelProvider` into its own class. This will allow you to override certain model-specific functionality. For example, a custom LLM invoke for Bedrock (the main reason I refactored)
Bedrock will now continue to generate tokens even if `max_tokens` is reached. Look at the following Python script and attached logs:
```python
from langchain.globals import set_debug, set_verbose
from kai.kai_config import KaiConfigModels, SupportedModelProviders
from kai.llm_interfacing.model_provider import ModelProvider
set_verbose(True)
set_debug(True)
m = ModelProvider.from_config(
config=KaiConfigModels(
provider=SupportedModelProviders.CHAT_BEDROCK,
args={"model_id": "us.anthropic.claude-3-5-sonnet-20241022-v2:0"},
)
) …
```

:sparkles: Added continuation support for Amazon Bedrock

---

kai/llm_interfacing/model_provider.py

:bug: Removed monkey patch, OpenShift AI now works with `max_completion_tokens`

---

kai/reactive_codeplanner/task_runner/compiler/maven_validator.py

* When doing comparison for collapsable errors, we assume that only the fields that matter are different, and everything else is reset.
* We were not reseting the column for collapsable errors, causing them to look different for both fuzzy match and equality.
* When it was unable to be solved, due to an error, we infinitly added parent task as a child task.
fixes #677

:bug: CollapsableErrors assume validation field values are empty

---

.trunk/configs/custom-words.txt
kai/reactive_codeplanner/agent/maven_compiler_fix/api.py
kai/reactive_codeplanner/task_manager/api.py
kai/reactive_codeplanner/task_manager/task_manager.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/task_runner.py
kai/reactive_codeplanner/task_runner/compiler/compiler_task_runner.py
kai/reactive_codeplanner/vfs/git_vfs.py
kai/reactive_codeplanner/vfs/repo_context_snapshot.py
kai/reactive_codeplanner/vfs/spawning_result.py
kai/rpc_server/server.py
tests/test_task_manager.py

* This will short circut the handling of a task when it is ignored to not add children
* Also added the logic to on moving a task to ignored, we revert the repo back to the state it was in when the task started.
* Had to remove the spawning result history from RepoContextSnapshot because of cycle imports of task -> RCS -> SpawningResult -> ReflectionTask -> task.

:sparkles: Handle retries and ignored tasks by not adding children

---

.github/workflows/build-and-push-binaries.yml
notebooks/followup_agent/00_do_followup_work.ipynb

Here are the results...ChatBedrock for llama models does NOT support tools. 
|   Kai Model Provider   |      Model       |  Works?  |
| ---------------------- | ---------------- | -------- |
| ChatOpenAI             | gpt-3.5-turbo    |  ✅  |
| ChatOpenAI (RH Maas)   | granite-8b       |  ✅  |
| ChatOpenAI (RH Maas)   | llama-3.1-8b      |  ✅  |
| ChatBedrock            | llama3-1-70b     |  ❌  |
| ChatBedrock            | llama3-2-70b     |  ❌ |
| ChatBedrock            | claude-3-sonnet  |  ✅  |
| ChatGoogleGenAI        | gemini-2.0-flash |  ✅  |
| ChatDeepSeek           | deepseek-chat    |  ✅  |
We have not tested the following providers yet:
* AzureChatOpenAI
* ChatOllama

👻  Validated tool usage with different providers
