konveyor/kai

.github/workflows/trunk-check-annotations.yml
.github/workflows/trunk-check.yml
Notes.md

Following guidance from https://github.com/trunk-io/trunk-action?tab=readme-ov-file#getting-inline-annotations-for-fork-prs

Adding trunk check to run on PRs

---

kai/scm.py
samples/fetch_apps.py
samples/generated_output/incident_store/cached_violations.yaml
samples/generated_output/incident_store/missing_incidents.yaml
samples/generated_output/incident_store/solved_incidents.yaml

Minor tweaks:
* Had to checkout quarkus branch in the fetch script for git diff to work 
* one of the git branch is '7.1' and it got interpreted as an integer which caused issues. So,  added `str(branch_name)` when obtaining the commit 
* updated incident store with latest analysis report data
Note: This PR might not be relevant after we merge Jonah's code and start using postgres

updating incident store

---

kai-service/mock-client.py
kai/data/jsonschema/post_get_incident_solution.json
kai/prompt_builder.py
kai/server.py

Action items/todos
- seed all datastore stuff
- make models swappable, config and all that
- add tests (lmao)
- make it easy to run

Preliminary end-to-end stuff

---

Makefile
requirements.txt

Update to work with MacOS

---

example/.gitignore
example/analyze.sh
example/debug_analysis_highlights.py
example/fetch.sh

The purpose of this PR is to begin to setup a place and scripts to help us migrate the CoolStore application.
Please see Issue #82 for context
Below will 
- Fetch our coolstore app
- Analyze it via Kantra
- Begin to look at the analysis output.yaml
- Parse the analysis data into markdown files for an easier way to view what issues are present (intent is to commit this to git to aid browsing repo and sharing info via GitHub)
- Look at the report from the perspective of what files are "impacted" and summarize the number of incidents seen per file
```
$ time ./debug_analysis_highlights.py 
/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from …
```

Initial setup for parsing Coolstore analysis to aid demo workflow

---

kai-service/mock-client.py
kai/data/jsonschema/get_incident_solutions_for_file.json
kai/prompt_builder.py
kai/pydantic_models.py
kai/server.py

We went with a naive approach of taking the list of incidents, and looping over them using the existing logic to process each incident, but passing the updated file forward.

Add preliminary batching support

---

kai/server.py

Only use exact matches in the prompt for now

---

kai/data/jsonschema/get_incident_solutions_for_file.json
kai/data/jsonschema/post_get_incident_solution.json
kai/server.py

Make incident snip optional

---

kai/embedding_provider.py
kai/incident_store_advanced.py
kai/kai_logging.py
kai/report.py
kai/result.py
kai/scm.py
kai/server.py

Really trying to get my lines committed to PR ratio up :muscle:

Fix -log arg

---

.gitignore
Makefile
example/README.md
example/run_demo.py
kai/capture.py
kai/kai_logging.py
kai/model_provider.py
kai/report.py
kai/scm.py
kai/server.py
tests/test_report.py

Related to #82 
A few things are addressed in this PR: (In hindsight I should have split things out into separate PRs)
- First cut at a client that parses analysis info for CoolStore and generates a requests per File with all incidents batched
- The response (received updated file) is saved and written to disk in the directory of the sample source code for Coolstore, so we are overwriting the exact file with the updates from Kai
- Tweaked logging in KAI Server to aid debugging and getting an idea of performance
- Added a Capture class to record data on server side to help us debug specific generated fixes
* Assumes you have the server running
1. `cd example`
2. `./fetch.sh`
3.  `source ../env/bin/activate`
4. `./run_demo.py`
Example of what the run_demo.py output looks like 
```
$ time …
```

CLI client to run through demo workflow on migrating Coolstore

---

Makefile
example/run_demo.py
kai/embedding_provider.py
kai/incident_store_advanced.py
kai/model_provider.py
kai/server.py
requirements.txt

This allows us to run it with Gunicorn and multiple workers, to better
handle concurrent requests.
Also Update client to make requests in parallel
Related to #100 
Blocked by #93

Make server WSGI compatible 

---

example/run_demo.py
kai/data/templates/mf_output_instructions.txt
kai/data/templates/output_instructions.txt
kai/pydantic_models.py
kai/server.py

Results can be seen here: https://github.com/konveyor-ecosystem/coolstore/pull/17/files

Ask LLM for additional information and include it in response

---

kai/data/templates/mf_preamble.txt

Updating the prompt along with values for the model appears to have resulted in improved results.
https://github.com/konveyor-ecosystem/coolstore/pull/19
Creating a PR in case others want to try to reproduce more positive results.
Open to hearing others results along with ideas on further improving this.

Update default preamble

---

README.md

Add documentation for DEMO_MODE

---

.trunk/trunk.yaml
kai/config.toml
kai/model_provider.py

Example of coolstore run here:
https://github.com/konveyor-ecosystem/coolstore/pull/26/files#

Enable testing with llama3

---

kai/server.py

Fixed prompt builder call site

---

kai/constants.py
kai/service/incident_store/incident_store.py

removing hard coded values 

---

requirements.txt

Upgrade Pydantic to fix issue with Python 3.12.4

---

build/Containerfile

Fix warning on docker build, issue #241

---

compose.yaml

Fixes #234 
Thank you @gtyellow for finding the issue and fix.

:bug: Fix for docker compose issue 234

---

kai/trace.py

:bug: Write trace data to local disk with podman compose up

---

kai/server.py

As I'm working up instructions for new users realized we don't have a good thing for users to read from logs to know when the server is ready to process a request.

👻 Log statement to show we are ready to receive requests

---

kai/service/incident_store/sql_types.py

Hotfix for a small oversight in the last PR.

:bug: Fix #252

---

.github/workflows/test-code-on-pr.yml
kai/service/incident_store/sql_types.py
requirements.txt
run_tests.sh
tests/test_always_fail.py

Implements #247 
Runs `run_test.py` automatically and generates coverage artifacts. To view the artifacts, click on the details for the Test Code PR run and then click on summary.

:sparkles: Added testing GitHub action

---

docs/scenarios/demo.md

Following this [PR #35](https://github.com/konveyor-ecosystem/coolstore/pull/35)
The demo doc is changed to point to minikube.

:book: change the demo doc to minikube

---

.github/workflows/evaluation.yml
kai/data/benchmarks/examples/example_a/application.yaml
kai/data/benchmarks/examples/example_a/incidents.yaml
kai/evaluation.py
kai/models/kai_config.py
kai/test_evaluation.py

:bug: Fixes #262

---

README.md

Update README.md for ROADMAP.md link

---

CONTRIBUTING.md
docs/contrib/Dev_Environment.md

Closes #273
Updated documentation to include new dependency management steps and virtual environment setup instructions as discussed in #255

Update documentation for dependency management and setup instructions

---

README.md
compose.yaml

These are temporary doc changes we need to unblock any new folks who are interested in running Kai

📖 README updates so folks may run stable as of today

---

README.md

Related to https://github.com/konveyor/kai/issues/287

📖 Add note on GENAI_KEY being required

---

example/run_demo.py

No idea how it was working for others. But in my environment, I had to bring this up to make sure all kai imports work

:bug: fix run_demo.py imports

---

kai/service/llm_interfacing/model_provider.py

Fix GENAI_KEY issue to allow demo_mode without requiring API key

---

kai/data/templates/solution_handling/before_and_after.jinja
kai/data/templates/solution_handling/diff_only.jinja
kai/data/templates/solution_handling/llm_summary.jinja
kai/models/util.py
kai/routes/load_analysis_report.py
kai/service/incident_store/incident_store.py
kai/service/incident_store/sql_types.py
kai/service/kai_application/kai_application.py
kai/service/llm_interfacing/model_provider.py
kai/service/solution_handling/consumption.py
kai/service/solution_handling/detection.py
kai/service/solution_handling/production.py
kai/service/solution_handling/test_detection.py
requirements.in
requirements.txt
tests/test_data/test_detection/test_line_match_simple/exact_matches.yaml
tests/test_data/test_detection/test_line_match_simple/new_added_incidents.java
tests/test_data/test_detection/test_line_match_simple/new_added_incidents.yaml
tests/test_data/test_detection/test_line_match_simple/new_added_whitespace.java
tests/test_data/test_detection/test_line_match_simple/new_added_whitespace.yaml
tests/test_data/test_detection/test_line_match_simple/new_exact_matches.java
tests/test_data/test_detection/test_line_match_simple/old_added_incidents.java
tests/test_data/test_detection/test_line_match_simple/old_added_incidents.yaml
tests/test_data/test_detection/test_line_match_simple/old_added_whitespace.java
tests/test_data/test_detection/test_line_match_simple/old_added_whitespace.yaml
tests/test_data/test_detection/test_line_match_simple/old_exact_matches.java
tests/util.py

Using https://github.com/JonahSussman/sequoia-diff to get tree mappings between ASTs.
Implements #298

:sparkles: Add Line Match algorithm and Fix Various Bugs

---

CONTRIBUTING.md

Confusion of how to run as a contributor was noticed while working #307, I think this change will help to avoid confusion for others.

📖 Update CONTRIBUTING.md to point reader at dev env setup doc

---

build/entrypoint.sh
compose.yaml

:sparkles: Add health checks to `compose.yaml`

---

playpen/repo_level_awareness/api.py
playpen/repo_level_awareness/codeplan.py
playpen/repo_level_awareness/maven_validator.py
playpen/repo_level_awareness/next_stuff.py

- Adds Maven validator
- Separates API and codeplan loop
- Plus the validator in so it's ready to feed to an agent
May supersede #362

Runnable codeplan loop

---

playpen/repo_level_awareness/git_vfs.py

I'd like to use GitPython, but using custom a work-tree and git-dir with is too hard.
As far as git licensing, as long as we don'd modify the source code and provide adequate attribution, I[ don't think there will be a problem](https://opensource.stackexchange.com/questions/7737/am-i-allowed-to-provide-compiled-binaries-of-open-source-libraries) as it git uses the LGPLv2 license.

:sparkles: Added "VFS" based on git

---

kai-analyzer/main.go
notebooks/kai-analyzer-code-plan/01_use_playpen_agent_with_coolstore.ipynb
playpen/client/anlalyzer_rpc.py
playpen/repo_level_awareness/api.py
playpen/repo_level_awareness/codeplan.py

- Decrease object logging verbosity
- Add documentation for next steps for demo that will use this

🐛 Fix kai-analyzer so that it can serve multiple requests

---

kai/jsonrpc/core.py
kai/jsonrpc/streams.py
kai/repo_level_awareness/task_runner/analyzer_lsp/task_runner.py
kai/repo_level_awareness/task_runner/analyzer_lsp/validator.py
notebooks/kai-analyzer-code-plan/01_config.toml
notebooks/kai-analyzer-code-plan/01_use_playpen_agent_with_coolstore.py

The stream handler was hanging on trying to decode its buffer because it started with whitespace. I fixed it by adding `self.buffer = self.buffer.lstrip()` to `BareJsonStream.get_from_buffer`.

:bug: Fixed bug with jsonrpc library

---

kai/reactive_codeplanner/task_manager/task_manager.py

- Also adds error handling around task management to avoid crashes

:sparkles: Validators now execute asnychronously

---

Makefile
kai/rpc_server/server.py

Adding ability for dependency rules to be set correctly in the seed

---

Makefile
kai/reactive_codeplanner/task_manager/api.py
kai/reactive_codeplanner/task_manager/priority_queue.py
kai/reactive_codeplanner/task_manager/task_manager.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/api.py

- add run_demo and run_debug_driver make targets
- add more metadata info to task string representation, including tracking parent priority + default priority
- report tasks in priority order when stringifying the queue
- increase verbosity when logging exceptions to aid debugging
- decrease verbosity of similarity logging, now only log when result is interesting

:ghost: Logging + Makefile improvements

---

Makefile
kai/analyzer.py
kai/reactive_codeplanner/main.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/api.py
kai/reactive_codeplanner/task_runner/compiler/maven_validator.py
kai/rpc_server/server.py

This should prevent non-duplicates from getting marked as duplicates.
Also includes a few changes to the debug driver and logging to aid debugging.

:bug: Stricter equality for analyzer issues

---

kai/analyzer.py
kai/constants.py
kai/reactive_codeplanner/task_runner/compiler/maven_validator.py
kai/reactive_codeplanner/vfs/git_vfs.py

- Added an ENV constant, with the pyinstaller python overrides removed
- All subprocess calls now use this
closes #521

:bug: Linux builds from CI now work

---

kai_analyzer_rpc/pkg/service/analyzer.go

Actually initializing the mutex and the cache when creating a new Analyzer

---

kai/analyzer.py
kai/reactive_codeplanner/task_manager/api.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/validator.py
kai/rpc_server/server.py
kai_analyzer_rpc/go.mod
kai_analyzer_rpc/go.sum
kai_analyzer_rpc/main.go
kai_analyzer_rpc/pkg/service/analyzer.go

Depends on https://github.com/konveyor/analyzer-lsp/pull/758

:sparkles: add support for excluding files / folders from analysis

---

kai/llm_interfacing/model_provider.py

See #558 for more info about how we can avoid doing these PRs in the future.

:sparkles: Added AzureChatOpenAI to ModelProvider

---

kai/rpc_server/server.py

Solves https://github.com/konveyor/kai/issues/572
Edit: The OpenAI api is down right now, the ci may fail, will retrigger it later.

🐛 fix windows paths replacements

---

kai_analyzer_rpc/pkg/service/analyzer.go

:bug:: Making the removal from cache in the same lock as the update

---

kai/reactive_codeplanner/task_runner/compiler/maven_validator.py

:bug: fix fuzzy equals for maven errors

---

kai/reactive_codeplanner/task_runner/dependency/task_runner.py

:bug: adding compiler error message to the dependency agent

---

kai_analyzer_rpc/pkg/service/analyzer.go

There is a small bug around intra-setting cache lock update.

:bug: set up locks more correctly

---

kai/llm_interfacing/model_provider.py

:bug: Fix healthcheck for bedrock claude

---

kai_analyzer_rpc/main.go

This fixes a situation where `kai_analyzer_rpc` tries to connect to Jaeger, even if `TRACING_ENABLED` is unset.

:bug: Fixed attempted Jaeger connection when tracing disabled

---

.trunk/configs/custom-words.txt
kai/rpc_server/main.py
kai_analyzer_rpc/pkg/tracing/init.go

* removes logs that waas cluttering up things

:bug: Adding back noop tracer for when the env-var is not set

---

kai/reactive_codeplanner/task_manager/task_manager.py
kai/rpc_server/server.py

* Adding chat messages to tell the user more detailed info on what is happening

:ghost: removing some chat messages that I think are too verbose

---

kai_analyzer_rpc/go.mod
kai_analyzer_rpc/go.sum

:bug: fixing windows path regex in analyzer-lsp

---

kai/reactive_codeplanner/task_runner/compiler/maven_validator.py

:bug: Handled slash added by Maven on Windows

---

kai/llm_interfacing/model_provider.py

* If we get a bad request error that is about max_completion_tokens, then we will monkey patch ChatOpenAI to prevent the automatic conversion of max_tokens to max_completion_tokens
supersedes bad change #685

Adding override for invoke_llm to ChatOpenAI to catch param conversion

---

kai/rpc_server/server.py

same needs to happen for encountered errors but that part is on the IDE side
Fixes #697 
Fixes #687

:bug: dedup modified files in overall result

---

kai/reactive_codeplanner/task_manager/api.py
kai/reactive_codeplanner/task_manager/task_manager.py
kai/reactive_codeplanner/task_runner/analyzer_lsp/api.py
kai/reactive_codeplanner/task_runner/compiler/maven_validator.py
kai/rpc_server/server.py

:sparkles: Add markdown rendering for tasks for communicating to frontend

---

kai/reactive_codeplanner/task_manager/task_manager.py
kai/rpc_server/server.py

:bug: Display successful / ignored tasks in the chat view correctly

---

kai_analyzer_rpc/go.mod
kai_analyzer_rpc/go.sum
kai_analyzer_rpc/main.go
kai_analyzer_rpc/pkg/rpc/server.go
kai_analyzer_rpc/pkg/service/analyzer.go
kai_analyzer_rpc/pkg/service/pipe_analyzer.go

Needs: https://github.com/konveyor/analyzer-lsp/pull/814
Calls NotifyFileChanges() in analyzer-lsp

:sparkles: Feature/notify file changes

---

.gitignore
.trunk/configs/custom-words.txt
kai/reactive_codeplanner/task_manager/task_manager.py
kai_mcp_solution_server/ts-mcp-client/package.json
kai_mcp_solution_server/ts-mcp-client/src/client.ts
kai_mcp_solution_server/ts-mcp-client/src/types/sdk.d.ts
kai_mcp_solution_server/ts-mcp-client/tsconfig.json
kai_solution_server/service/incident_store/backend.py

Add example typescript client for solution server

---

kai_mcp_solution_server/Makefile
kai_mcp_solution_server/README.md
kai_mcp_solution_server/tests/__init__.py
kai_mcp_solution_server/tests/mcp_client.py
kai_mcp_solution_server/tests/ssl_utils.py
kai_mcp_solution_server/tests/test_integration.py
kai_mcp_solution_server/ts-mcp-client/README.md
kai_mcp_solution_server/ts-mcp-client/package-lock.json
kai_mcp_solution_server/ts-mcp-client/package.json
kai_mcp_solution_server/ts-mcp-client/src/client.ts
kai_mcp_solution_server/uv.lock

Add support and tests for an MCP server that requires authorization
